### ISSUE TITLE
make didn't finish succesfully

### ISSUE THREAD

**Issue by bit-scientist** [SmitSheth/People-Counter#1]
I git-cloned this repo into my Ubuntu 16.04 with **Opencv 3.1.0**, **CUDA 8.0**
When I type `make` in **_darkent_** directory as you pointed out, it throws an error like below
```
gcc -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -shared obj/gemm.o obj/utils.o obj/cuda.o obj/deconvolutional_layer.o obj/convolutional_layer.o obj/list.o obj/image.o obj/activations.o obj/im2col.o obj/col2im.o obj/blas.o obj/crop_layer.o obj/dropout_layer.o obj/maxpool_layer.o obj/softmax_layer.o obj/data.o obj/matrix.o obj/network.o obj/connected_layer.o obj/cost_layer.o obj/parser.o obj/option_list.o obj/detection_layer.o obj/route_layer.o obj/upsample_layer.o obj/box.o obj/normalization_layer.o obj/avgpool_layer.o obj/layer.o obj/local_layer.o obj/shortcut_layer.o obj/logistic_layer.o obj/activation_layer.o obj/rnn_layer.o obj/gru_layer.o obj/crnn_layer.o obj/demo.o obj/batchnorm_layer.o obj/region_layer.o obj/reorg_layer.o obj/tree.o obj/lstm_layer.o obj/l2norm_layer.o obj/yolo_layer.o obj/iseg_layer.o obj/image_opencv.o -o libdarknet.so -lm -pthread  `pkg-config --libs opencv` -lstdc++
/usr/bin/ld: cannot find -lippicv
collect2: error: ld returned 1 exit status
Makefile:83: recipe for target 'libdarknet.so' failed
make: *** [libdarknet.so] Error 1
```
Your advice on that issue?
Thank you!

**Comment by SmitSheth** [comment]
It seems there is a problem with your opencv installation. libippicv.a is a third party library, so you need to explicitly provide it during compilation or make it part of your execution environment. Recompile opencv with following option **cmake -DWITH_IPP=ON . && make -j $(nproc) && make install**

If you don't require that library then the solution is simply to remove -lippicv from opencv pkg-config configuration file. So you have to locate opencv.pc file, which default is in /usr/local/lib/pkgconfig/ directory. Then from section Libs: just remove the aforementioned library.

**Comment by bit-scientist** [comment]
@SmitSheth Thank you for a quick reply.
I did as same as you advised. `Make` ended successfully since there was no error whatsoever.
