### ISSUE TITLE
Compile error against OpenCV 4.x+ requires enabled C++11 support

### ISSUE THREAD

**Issue by huzhiren** [SmitSheth/People-Counter#3]
I have opencv4 installed in mac, try to compile (after change opencv2 to opencv4):

`
In file included from ./src/image.c:25:
In file included from /usr/local/Cellar/opencv/4.0.1/include/opencv4/opencv2/core/types_c.h:82:
/usr/local/Cellar/opencv/4.0.1/include/opencv4/opencv2/core/cvdef.h:656:4: fatal error: "OpenCV 4.x+ requires enabled C++11 support"
#  error "OpenCV 4.x+ requires enabled C++11 support"
   ^
1 error generated.
make: *** [obj/image.o] Error 1`

Then  if I add -std=c++11 in the CFLAGS I will get this error:
`error: invalid argument '-std=c++11' not allowed with 'C'
make: *** [obj/gemm.o] Error 1`

**Comment by SmitSheth** [comment]
@huzhiren This seems to be opencv error. Try using opencv version <3.4.0 since in opencv 4 they have some deprecated C apis. You can refer this issue for possible fixes : https://github.com/pjreddie/darknet/issues/691

**Comment by huzhiren** [comment]
@SmitSheth thanks for your prompt reply.    I think you are right, switch to opencv3.4 is the easiest way.  Darknet has c files.
