### ISSUE TITLE
annotate image.C please!

### ISSUE THREAD

**Issue by renguoyin123** [SmitSheth/People-Counter#8]
Can you annotate detailed the changes you made in file image.c ? What's the author's version of OPENCV? I'm running yolov3 on windows 10 and vs2015, so it's a little tricky，This is darknet when the release of the version, image.C and image.h file in the definition of the function is very different

**Comment by adamgan919191** [comment]
do you got the solution?

**Comment by renguoyin123** [comment]
There's a problem with the author's Code. I hope he uploads windows soon
