### ISSUE TITLE
modified file and compatible os? 

### ISSUE THREAD

**Issue by adamgan919191** [SmitSheth/People-Counter#9]
Hye sir, I have a few question regarding on this repo.

1) Do it works in windows or only work for Ubuntu only?
2) What the original file have you modified?

**Comment by renguoyin123** [comment]
You can't run it directly. You need to change the code.

**Comment by adamgan919191** [comment]
which code i i need to change

**Comment by SmitSheth** [comment]
> Hye sir, I have a few question regarding on this repo.
> 
> 1. Do it works in windows or only work for Ubuntu only?
> 2. What the original file have you modified?

Hey, currently the repository runs on Ubuntu systems only. Windows is not supported
